# Generated by Django 3.2.25 on 2025-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250422_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
